In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(3, 4, 5).type(torch.FloatTensor)
a

tensor([[[0.4384, 0.9078, 0.4584, 0.5819, 0.7299],
         [0.8598, 0.7653, 0.3665, 0.2073, 0.4775],
         [0.6301, 0.3100, 0.2265, 0.3083, 0.7970],
         [0.3084, 0.3669, 0.0611, 0.5365, 0.9313]],

        [[0.1098, 0.1009, 0.0378, 0.5035, 0.0102],
         [0.9877, 0.5743, 0.2242, 0.2292, 0.6485],
         [0.2925, 0.6018, 0.5296, 0.2996, 0.0909],
         [0.7969, 0.4644, 0.7722, 0.7980, 0.0447]],

        [[0.3942, 0.2858, 0.1519, 0.9853, 0.5960],
         [0.6587, 0.1155, 0.2570, 0.6450, 0.9850],
         [0.5000, 0.7721, 0.2400, 0.8658, 0.3433],
         [0.3455, 0.2629, 0.6242, 0.3768, 0.3184]]])

In [3]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)
a

tensor([[0.4384, 0.9078, 0.4584, 0.5819, 0.7299, 0.8598, 0.7653, 0.3665, 0.2073,
         0.4775],
        [0.6301, 0.3100, 0.2265, 0.3083, 0.7970, 0.3084, 0.3669, 0.0611, 0.5365,
         0.9313],
        [0.1098, 0.1009, 0.0378, 0.5035, 0.0102, 0.9877, 0.5743, 0.2242, 0.2292,
         0.6485],
        [0.2925, 0.6018, 0.5296, 0.2996, 0.0909, 0.7969, 0.4644, 0.7722, 0.7980,
         0.0447],
        [0.3942, 0.2858, 0.1519, 0.9853, 0.5960, 0.6587, 0.1155, 0.2570, 0.6450,
         0.9850],
        [0.5000, 0.7721, 0.2400, 0.8658, 0.3433, 0.3455, 0.2629, 0.6242, 0.3768,
         0.3184]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(5, size=(10,))
b

tensor([2, 2, 2, 0, 1, 4, 0, 3, 4, 3])

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b

tensor([[0.8769, 1.8156, 0.9168, 0.0000, 0.7299, 3.4391, 0.0000, 1.0996, 0.8291,
         1.4326],
        [1.2602, 0.6199, 0.4529, 0.0000, 0.7970, 1.2338, 0.0000, 0.1832, 2.1462,
         2.7938],
        [0.2195, 0.2018, 0.0756, 0.0000, 0.0102, 3.9509, 0.0000, 0.6726, 0.9168,
         1.9456],
        [0.5851, 1.2035, 1.0592, 0.0000, 0.0909, 3.1876, 0.0000, 2.3165, 3.1921,
         0.1341],
        [0.7884, 0.5715, 0.3039, 0.0000, 0.5960, 2.6349, 0.0000, 0.7710, 2.5801,
         2.9549],
        [1.0000, 1.5442, 0.4799, 0.0000, 0.3433, 1.3821, 0.0000, 1.8726, 1.5072,
         0.9552]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
a.mm(a.t())

tensor([[3.8279, 2.5468, 2.1855, 2.6683, 2.8633, 2.7417],
        [2.5468, 2.6632, 1.5283, 1.5887, 2.6748, 1.8891],
        [2.1855, 1.5283, 2.1061, 1.7034, 2.1412, 1.5064],
        [2.6683, 1.5887, 1.7034, 2.9120, 2.0529, 2.2229],
        [2.8633, 2.6748, 2.1412, 2.0529, 3.4857, 2.4869],
        [2.7417, 1.8891, 1.5064, 2.2229, 2.4869, 2.5927]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)
y = x**3 + z - 75 * t
y.backward()
print(y.grad)

None


/Users/maximdoroshenko/opt/anaconda3/lib/python3.8/site-packages/torch/_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /Users/distiller/project/pytorch/build/aten/src/ATen/core/TensorBody.h:475.)
  return self._grad


In [9]:
x = torch.tensor([1.0, 0.5, 2], requires_grad=True)
z = t = torch.ones(3, requires_grad=True)
y = x**3 + z - 75 * t
y.backward(x)
print(y.grad)

None


In [10]:
# 8. Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
# 9. Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)